### ISSUE TITLE
Exception - processing 01 - Invididual.csv

### ISSUE THREAD

**Issue by spurgeonbj** [KingdomFirst/Bulldozer#2]
Hi,

While attempting to import Individual data, faced the following exception.
`23-03-2019 09:45:45,Next Page,"System.NullReferenceException: Object reference not set to an instance of an object.
   at Bulldozer.SelectPage..ctor(BulldozerComponent parameter)
   at Bulldozer.ConnectPage.btnNext_Click(Object sender, RoutedEventArgs e)"
23-03-2019 09:46:21,Next Page,"System.NullReferenceException: Object reference not set to an instance of an object.
   at Bulldozer.SelectPage..ctor(BulldozerComponent parameter)
   at Bulldozer.ConnectPage.btnNext_Click(Object sender, RoutedEventArgs e)"
23-03-2019 14:57:55,Transform Data,"System.Data.SqlClient.SqlException (0x80131904): Invalid object name 'dbo.DefinedValue'.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   at System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TTarget,TInterceptionContext,TResult](TTarget target, Func`3 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed)
   at System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.Reader(DbCommand command, DbCommandInterceptionContext interceptionContext)
   at System.Data.Entity.Core.EntityClient.Internal.EntityCommandDefinition.ExecuteStoreCommands(EntityCommand entityCommand, CommandBehavior behavior)
ClientConnectionId:5dacb72c-d9d4-4261-b37d-f460e55c537a
Error Number:208,State:1,Class:16"
`

**Comment by spurgeonbj** [comment]
Hi, Shalom!
Today's update...
Realised null exceptions and deleted all columns with null data.
This proceeded further.
Was able to reach the finish screen
`20:41:34  Starting health checks...
20:41:48  Checking for existing people...
20:41:52  Starting data import...
20:41:53  Starting Individual import (0 already exist).
20:41:53  Could not finish upload. Check the exceptions log for details.`

Got exception during transformation phase with 
`
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Bulldozer.CSV.CSVComponent.LoadIndividuals(CSVInstance csvData)
   at Bulldozer.CSV.CSVComponent.TransformData(Dictionary2 settings)
   at Bulldozer.ProgressPage.bwImportData_DoWork(Object sender, DoWorkEventArgs e)
`

**Comment by spurgeonbj** [comment]
Guess it expects a fixed number of columns ...

**Comment by spurgeonbj** [comment]
![Bulldozer-Import-Error-1-20190324](https://user-images.githubusercontent.com/6739161/54881492-925a2700-4e76-11e9-833c-8cd0091c01c4.png)

**Comment by spurgeonbj** [comment]
Hi. Today's update! 

Realised that structure of source expected is as per Sample CSVs ([https://github.com/KingdomFirst/Bulldozer/tree/master/Bulldozer.CSV/SampleCSVs](https://github.com/KingdomFirst/Bulldozer/tree/master/Bulldozer.CSV/SampleCSVs))

So, when creating a sheet with data / structure exactly as the given 01 - Individual.csv, it went through successfully.

![Bulldozer-Import-1-20190325](https://user-images.githubusercontent.com/6739161/54896018-2c0dec80-4ee8-11e9-8024-63cf88582724.png)

Thanks for the nice tool!

**Comment by treyhendon** [comment]
Sorry about that confusion!  Glad you were able to get it.  Apologies that the Wiki is not fully built out.  I will be working on that in the coming weeks.

Overall, yes, that [README](https://github.com/KingdomFirst/Bulldozer/blob/master/Bulldozer.CSV/SampleCSVs/README.md) file is the best documentation at this point.

**Comment by spurgeonbj** [comment]
Dear Trey,

Shalom!!

Thanks a ton for your kind response!!

No problem at all!! It was a great learning experience.

Thanks to your efforts, we have successfully imported some data.

May our dear Lord continue to lead you mightily in His Kingdom building
efforts!

Sincere, warm regards
