### ISSUE TITLE
B: Binary import fails

### ISSUE THREAD

**Issue by lauweijie** [KingdomFirst/Bulldozer#38]
Please answer the following questions for yourself before submitting an issue. 

- [x ] I have classified my issue according to the following rules:

**Bug Classifications:**

_Enhancement:_ A desired change to the code that enhances functionality verses fixing an issue.   

_Bug:_ Updating code to work as originally designed.

- [x] I am running the latest version
- [x] I checked to make sure that this issue has not already been filed
- [x] I've named my issue either `B:` or `E:` depending on whether it is a bug or an enhancement

# Expected Behavior

Able to import binary files

# Current Behavior

Unable to import binary files. Bulldozer terminates with error (see below).

# Failure Information (for bugs)

The column has been renamed from `AllowCaching` to `CacheToServerFileSystem`.

https://github.com/SparkDevNetwork/Rock/blob/edc98874c9d83b0057665789d1649634c0a10973/Rock.Migrations/Migrations/Version%2011.0/Version%201.11.0/202006051339147_BinaryFileTypeCachingChanges.cs#L32

## Steps to Reproduce

Please provide detailed steps for reproducing the issue. 

1. Attempt to import binary files as per instruction

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Rock Version: 11.2
* Bulldozer Version: v1.10.2.3.20200615
* SQL Server Version: SQL Server 2019
* Windows Version: Windows Server 2019

## Failure Logs

```
1/11/2020 8:25:58 AM,Transform Data,"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'AllowCaching'.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   at System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TTarget,TInterceptionContext,TResult](TTarget target, Func`3 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed)
   at System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.Reader(DbCommand command, DbCommandInterceptionContext interceptionContext)
   at System.Data.Entity.Core.EntityClient.Internal.EntityCommandDefinition.ExecuteStoreCommands(EntityCommand entityCommand, CommandBehavior behavior)
ClientConnectionId:50f8b11c-6ef1-4db6-bf10-b1ca6aa15ca2
Error Number:207,State:1,Class:16"
```

**Comment by nateh777** [comment]
Due to other priorities we have not yet confirmed v11 support with Bulldozer. Please be aware there may be other things that are not working properly with it yet. We support up to 10.2 currently. Thank you for the report.

**Comment by treyhendon** [comment]
Hey @lauweijie I'm working on a v11.3 branch now that it is in general release.  The good news is that the import does still work with the old name and it's just indicating deprecated in VisualStudio.  But, the even better news is that once the v11 update branch is in master, we can take your PR where you've renamed the property (thanks!!).
