### ISSUE TITLE
B: CSV: Can't import Families CSV 

### ISSUE THREAD

**Issue by JohnMcNail** [KingdomFirst/Bulldozer#49]
# Expected Behavior

Import of Families CSV File 

# Current Behavior

After selecting next in the bulldozer UI an error occurs. 

# Failure Information (for bugs)

System.NullReferenceException: Object reference not set to an instance of an object.
   at Bulldozer.SelectPage..ctor(BulldozerComponent parameter)
   at Bulldozer.ConnectPage.btnNext_Click(Object sender, RoutedEventArgs e)

## Steps to Reproduce

Please provide detailed steps for reproducing the issue. 

1. select csv
2. upload csv
3. connect to dev instance
4. hit next

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Rock Version: Rock McKinley 11.4
* Bulldozer Version: v1.11.3.1
* SQL Server Version: 
* Windows Version:

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by JohnMcNail** [comment]
Resolved. Remember to close your csv before trying to run the bulldozer...... doh!
