### ISSUE TITLE
B: Import error "Invalid column name 'Summary'"

### ISSUE THREAD

**Issue by apull** [KingdomFirst/Bulldozer#82]
When attempting to import an Individual.csv file, I get an error about an invalid column name 'Summary'

On latest versions of both Bulldozer and Rock. SQL 2019 express, Server 2019

1. Using template provide, upload .csv and connect to database.  Verify first record looks good and submit.
2. Passes health checks, fails after/on "Checking for existing data..." with error "Could not finish upload..."
3. Exception log data below.  Not sure where column name 'Summary' is coming from, certainly it is not present in the upload file.

3/19/2023 5:22:49 PM,Transform Data,"System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'Summary'.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   at System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TTarget,TInterceptionContext,TResult](TTarget target, Func`3 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed)
   at System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.Reader(DbCommand command, DbCommandInterceptionContext interceptionContext)
   at System.Data.Entity.Core.EntityClient.Internal.EntityCommandDefinition.ExecuteStoreCommands(EntityCommand entityCommand, CommandBehavior behavior)
ClientConnectionId:b5fcf164-5810-47f1-be2c-1b44cf36b373
Error Number:207,State:1,Class:16"

**Comment by apull** [comment]
Thanks, that explains the problem--we are on Rock 13.7.  Unfortunately compiling from the github repository is a bit beyond my skills and available tools at this point.  I appreciate your help.

**Comment by apull** [comment]
Yes, that helps.  Thank you so much, the import worked perfectly.
